version: 1.33.{build}
skip_non_tags: true
image: Visual Studio 2019
environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
configuration:
- Release
platform: Any CPU
build:
  project: para-client-csharp.sln
  verbosity: normal
  publish_nuget: true
test: off
before_build:
  - nuget restore para-client-csharp.sln
after_build:
  - nuget pack "para-client-csharp\para-client-csharp.csproj" -version "%APPVEYOR_BUILD_VERSION%" -Symbols
  - appveyor PushArtifact "para_client_csharp.%APPVEYOR_BUILD_VERSION%.nupkg"
  - appveyor PushArtifact "para_client_csharp.%APPVEYOR_BUILD_VERSION%.symbols.nupkg"
