version: 1.33.{build}
skip_non_tags: true
image: Visual Studio 2019
environment:
  VisualStudioVersion: 15.0
  BuildConfiguration: release
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
configuration:
- Release
platform: Any CPU
artifacts:
  - path: '**\*.nupkg'
build:
  project: para-client-csharp.sln
  verbosity: normal
  publish_core_console: true
  publish_nuget: true
  publish_nuget_symbols: true
deploy:
- provider: NuGet
  api_key:
    secure: MXJfg0wgB+rI0MTloy2RsrHyjib8aE7HO9sJxHldahzo6mTm96IdEZOpkEsPI5fy
test: off
before_build:
  - nuget restore para-client-csharp.sln

