version: 1.17.{build}
skip_tags: true
os: Visual Studio 2015
build:
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: 0a0ZfngLKNjf/OTs6QxmAnrstMt46iVXeRydj7I/pnlRQWgZ9DSf8e074HaMV/hO