version: 1.17.{build}
skip_tags: true
os: Visual Studio 2015
build:
  verbosity: minimal
test: off
deploy:
- provider: NuGet
  api_key:
    secure: 0a0ZfngLKNjf/OTs6QxmAnrstMt46iVXeRydj7I/pnlRQWgZ9DSf8e074HaMV/hO
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore para-client-csharp.sln
after_build:
  - nuget pack "%APPVEYOR_BUILD_FOLDER%\para-client-csharp\para-client-csharp\para-client-csharp.csproj" -version "%GitVersion_NuGetVersion%" -Symbols
  - appveyor PushArtifact "para-client-csharp.%GitVersion_NuGetVersion%.nupkg"
  - appveyor PushArtifact "para-client-csharp.%GitVersion_NuGetVersion%.symbols.nupkg"
